name: Julia TagBot
author: Chris de Graaf
description: Creates GitHub releases for your registered Julia packages
inputs:
  token:
    description: GitHub API token
    required: true
  registry:
    description: Owner/name of the registry repository
    required: false
    default: JuliaRegistries/General
  dispatch:
    description: Whether or not to create a repository dispatch event prior to making releases
    required: false
    default: false
  changelog:
    description: Changelog template
    required: false
    default: |
      ## {{ package }} {{ version }}

      [Diff since {{ previous_release }}]({{ compare_url }})

      {% if custom %}
      {{ custom }}
      {% endif %}

      {%if issues %}
      **Closed issues:**
      {% for issue in issues %}
      - {{ issue.title }} (#{{ issue.number }})
      {% endfor %}
      {% endif %}

      {%if pulls %}
      **Merged pull requests:**
      {% for pull in pulls %}
      - {{ pull.title }} (#{{ pull.number }}) (@{{ pull.author.username }})
      {% endfor %}
      {% endif %}
runs:
  using: docker
  image: docker://degraafc/tagbot:1
branding:
  icon: tag
  color: red
