name: Label Error Reports
on:
  issues:
    types: opened
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: adamzolyak/issue-labeler-action@2.0.1
        if: contains(github.event.issue.title, 'Automatic error report')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
